openapi: 3.0.1
info:
  title: services/auth_proxy/v1/proxy_api.proto
  description: Authentication Proxy Service API
  version: "1.0"
servers:
  - url: https://authproxy.turnkey.com
tags:
  - name: AuthProxyService
  - name: Accounts
    description: Account management operations
  - name: Auth
    description: Authentication operations
  - name: Sessions
    description: Session management operations
  - name: Wallet Kit
    description: Wallet kit configuration
paths:
  /v1/account:
    post:
      tags:
        - Accounts
      summary: Get Account
      description: Return organization id associated with a given phone number, email, public key, credential ID or OIDC token.
      operationId: GetAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAccountRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/oauth2_authenticate:
    post:
      tags:
        - Auth
      summary: OAuth 2.0 Authenticate
      description: Authenticate with an OAuth 2.0 provider and receive an OIDC token issued by Turnkey in response.
      operationId: OAuth2Authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuth2AuthenticateRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuth2AuthenticateResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/oauth_login:
    post:
      tags:
        - Sessions
      summary: OAuth Login
      description: Login using an OIDC token and public key.
      operationId: OAuthLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthLoginRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthLoginResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/otp_init:
    post:
      tags:
        - Auth
      summary: Init OTP
      description: Initialize an OTP (email or SMS) for a user.
      operationId: InitOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitOtpRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitOtpResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/otp_login:
    post:
      tags:
        - Sessions
      summary: OTP Login
      description: Login using a verification token and public key.
      operationId: OtpLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpLoginRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpLoginResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/otp_verify:
    post:
      tags:
        - Auth
      summary: Verify OTP
      description: Verify the OTP code previously sent to the user's contact and return a verification token.
      operationId: VerifyOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtpRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOtpResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/signup:
    post:
      tags:
        - Auth
      summary: Signup
      description: Onboard a new user.
      operationId: Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

  /v1/wallet_kit_config:
    post:
      tags:
        - Wallet Kit
      summary: Get WalletKit Config
      description: Get wallet kit settings and feature toggles for the calling organization.
      operationId: GetWalletKitConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetWalletKitConfigRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWalletKitConfigResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RpcStatus'

components:
  schemas:
    ProtobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties: true

    RpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ProtobufAny'

    AddressFormat:
      type: string
      enum:
        - ADDRESS_FORMAT_UNCOMPRESSED
        - ADDRESS_FORMAT_COMPRESSED
        - ADDRESS_FORMAT_ETHEREUM
        - ADDRESS_FORMAT_SOLANA
        - ADDRESS_FORMAT_COSMOS
        - ADDRESS_FORMAT_TRON
        - ADDRESS_FORMAT_SUI
        - ADDRESS_FORMAT_APTOS
        - ADDRESS_FORMAT_BITCOIN_MAINNET_P2PKH
        - ADDRESS_FORMAT_BITCOIN_MAINNET_P2SH
        - ADDRESS_FORMAT_BITCOIN_MAINNET_P2WPKH
        - ADDRESS_FORMAT_BITCOIN_MAINNET_P2WSH
        - ADDRESS_FORMAT_BITCOIN_MAINNET_P2TR
        - ADDRESS_FORMAT_BITCOIN_TESTNET_P2PKH
        - ADDRESS_FORMAT_BITCOIN_TESTNET_P2SH
        - ADDRESS_FORMAT_BITCOIN_TESTNET_P2WPKH
        - ADDRESS_FORMAT_BITCOIN_TESTNET_P2WSH
        - ADDRESS_FORMAT_BITCOIN_TESTNET_P2TR
        - ADDRESS_FORMAT_BITCOIN_SIGNET_P2PKH
        - ADDRESS_FORMAT_BITCOIN_SIGNET_P2SH
        - ADDRESS_FORMAT_BITCOIN_SIGNET_P2WPKH
        - ADDRESS_FORMAT_BITCOIN_SIGNET_P2WSH
        - ADDRESS_FORMAT_BITCOIN_SIGNET_P2TR
        - ADDRESS_FORMAT_BITCOIN_REGTEST_P2PKH
        - ADDRESS_FORMAT_BITCOIN_REGTEST_P2SH
        - ADDRESS_FORMAT_BITCOIN_REGTEST_P2WPKH
        - ADDRESS_FORMAT_BITCOIN_REGTEST_P2WSH
        - ADDRESS_FORMAT_BITCOIN_REGTEST_P2TR
        - ADDRESS_FORMAT_SEI
        - ADDRESS_FORMAT_XLM
        - ADDRESS_FORMAT_DOGE_MAINNET
        - ADDRESS_FORMAT_DOGE_TESTNET
        - ADDRESS_FORMAT_TON_V3R2
        - ADDRESS_FORMAT_TON_V4R2
        - ADDRESS_FORMAT_TON_V5R1
        - ADDRESS_FORMAT_XRP

    ApiKeyCurve:
      type: string
      enum:
        - API_KEY_CURVE_P256
        - API_KEY_CURVE_SECP256K1
        - API_KEY_CURVE_ED25519

    ApiKeyParamsV2:
      type: object
      required:
        - apiKeyName
        - publicKey
        - curveType
      properties:
        apiKeyName:
          type: string
          description: Human-readable name for an API Key.
        publicKey:
          type: string
          description: The public component of a cryptographic key pair used to sign messages and transactions.
        curveType:
          $ref: '#/components/schemas/ApiKeyCurve'
        expirationSeconds:
          type: string
          description: Optional window (in seconds) indicating how long the API Key should last.

    Attestation:
      type: object
      required:
        - credentialId
        - clientDataJson
        - attestationObject
        - transports
      properties:
        credentialId:
          type: string
          description: The cbor encoded then base64 url encoded id of the credential.
        clientDataJson:
          type: string
          description: A base64 url encoded payload containing metadata about the signing context and the challenge.
        attestationObject:
          type: string
          description: A base64 url encoded payload containing authenticator data and any attestation the webauthn provider chooses.
        transports:
          type: array
          items:
            $ref: '#/components/schemas/AuthenticatorTransport'
          description: The type of authenticator transports.

    AuthenticatorParamsV2:
      type: object
      required:
        - authenticatorName
        - challenge
        - attestation
      properties:
        authenticatorName:
          type: string
          description: Human-readable name for an Authenticator.
        challenge:
          type: string
          description: Challenge presented for authentication purposes.
        attestation:
          $ref: '#/components/schemas/Attestation'

    AuthenticatorTransport:
      type: string
      enum:
        - AUTHENTICATOR_TRANSPORT_BLE
        - AUTHENTICATOR_TRANSPORT_INTERNAL
        - AUTHENTICATOR_TRANSPORT_NFC
        - AUTHENTICATOR_TRANSPORT_USB
        - AUTHENTICATOR_TRANSPORT_HYBRID

    Curve:
      type: string
      enum:
        - CURVE_SECP256K1
        - CURVE_ED25519

    GetAccountRequest:
      type: object
      required:
        - filterType
        - filterValue
      properties:
        filterType:
          type: string
          description: Specifies the type of filter to apply, i.e 'CREDENTIAL_ID', 'NAME', 'USERNAME', 'EMAIL', 'PHONE_NUMBER', 'OIDC_TOKEN' or 'PUBLIC_KEY'
        filterValue:
          type: string
          description: The value of the filter to apply for the specified type. For example, a specific email or name string.

    GetAccountResponse:
      type: object
      required:
        - organizationId
      properties:
        organizationId:
          type: string

    GetWalletKitConfigRequest:
      type: object

    GetWalletKitConfigResponse:
      type: object
      required:
        - enabledProviders
        - sessionExpirationSeconds
        - organizationId
      properties:
        enabledProviders:
          type: array
          items:
            type: string
          description: List of enabled authentication providers (e.g., 'facebook', 'google', 'apple', 'email', 'sms', 'passkey', 'wallet')
        sessionExpirationSeconds:
          type: string
          description: Session expiration duration in seconds
        organizationId:
          type: string
          description: The organization ID this configuration applies to
        oauthClientIds:
          type: object
          additionalProperties:
            type: string
          description: Mapping of social login providers to their OAuth client IDs.
        oauthRedirectUrl:
          type: string
          description: OAuth redirect URL to be used for social login flows.
        otpAlphanumeric:
          type: boolean
        otpLength:
          type: string

    InitOtpRequest:
      type: object
      required:
        - otpType
        - contact
      properties:
        otpType:
          type: string
          description: Enum to specifiy whether to send OTP via SMS or email
        contact:
          type: string
          description: Email or phone number to send the OTP code to

    InitOtpResponse:
      type: object
      required:
        - otpId
      properties:
        otpId:
          type: string
          description: Unique identifier for an OTP authentication

    OAuth2AuthenticateRequest:
      type: object
      required:
        - provider
        - authCode
        - redirectUri
        - codeVerifier
        - clientId
      properties:
        provider:
          $ref: '#/components/schemas/Oauth2Provider'
        authCode:
          type: string
          description: The auth_code provided by the OAuth 2.0 to the end user to be exchanged for a Bearer token in the OAuth 2.0 flow
        redirectUri:
          type: string
          description: The URI the user is redirected to after they have authenticated with the OAuth 2.0 provider
        codeVerifier:
          type: string
          description: The code verifier used by OAuth 2.0 PKCE providers
        nonce:
          type: string
          description: An optional nonce used by the client to prevent replay/substitution of an ID token
        clientId:
          type: string
          description: The client ID registered with the OAuth 2.0 provider

    OAuth2AuthenticateResponse:
      type: object
      required:
        - oidcToken
      properties:
        oidcToken:
          type: string

    Oauth2Provider:
      type: string
      enum:
        - OAUTH2_PROVIDER_X
        - OAUTH2_PROVIDER_DISCORD

    OAuthLoginRequest:
      type: object
      required:
        - oidcToken
        - publicKey
      properties:
        oidcToken:
          type: string
        publicKey:
          type: string
        invalidateExisting:
          type: boolean
        organizationId:
          type: string

    OAuthLoginResponse:
      type: object
      required:
        - session
      properties:
        session:
          type: string

    OauthProviderParams:
      type: object
      required:
        - providerName
        - oidcToken
      properties:
        providerName:
          type: string
        oidcToken:
          type: string

    OtpLoginRequest:
      type: object
      required:
        - verificationToken
        - publicKey
      properties:
        verificationToken:
          type: string
        publicKey:
          type: string
        invalidateExisting:
          type: boolean
        organizationId:
          type: string
        clientSignature:
          type: string

    OtpLoginResponse:
      type: object
      required:
        - session
      properties:
        session:
          type: string

    PathFormat:
      type: string
      enum:
        - PATH_FORMAT_BIP32

    SignupRequest:
      type: object
      required:
        - apiKeys
        - authenticators
        - oauthProviders
      properties:
        userEmail:
          type: string
        userPhoneNumber:
          type: string
        userTag:
          type: string
        userName:
          type: string
        organizationName:
          type: string
        verificationToken:
          type: string
        apiKeys:
          type: array
          items:
            $ref: '#/components/schemas/ApiKeyParamsV2'
          description: A list of API Key parameters. This field, if not needed, should be an empty array in your request body.
        authenticators:
          type: array
          items:
            $ref: '#/components/schemas/AuthenticatorParamsV2'
          description: A list of Authenticator parameters. This field, if not needed, should be an empty array in your request body.
        oauthProviders:
          type: array
          items:
            $ref: '#/components/schemas/OauthProviderParams'
          description: A list of Oauth providers. This field, if not needed, should be an empty array in your request body.
        wallet:
          $ref: '#/components/schemas/WalletParams'

    SignupResponse:
      type: object
      required:
        - organizationId
        - userId
      properties:
        organizationId:
          type: string
        wallet:
          $ref: '#/components/schemas/WalletResult'
        userId:
          type: string
          description: Root user ID created for this sub-organization

    VerifyOtpRequest:
      type: object
      required:
        - otpId
        - otpCode
      properties:
        otpId:
          type: string
          description: ID representing the result of an init OTP activity.
        otpCode:
          type: string
          description: OTP sent out to a user's contact (email or SMS)
        publicKey:
          type: string
          description: Client-side public key generated by the user, which will be added to the JWT response and verified in subsequent requests via a client proof signature

    VerifyOtpResponse:
      type: object
      required:
        - verificationToken
      properties:
        verificationToken:
          type: string
          description: Signed JWT containing a unique id, expiry, verification type, contact. Verification status of a user is updated when the token is consumed (in OTP_LOGIN requests)

    WalletAccountParams:
      type: object
      required:
        - curve
        - pathFormat
        - path
        - addressFormat
      properties:
        curve:
          $ref: '#/components/schemas/Curve'
        pathFormat:
          $ref: '#/components/schemas/PathFormat'
        path:
          type: string
          description: Path used to generate a wallet Account.
        addressFormat:
          $ref: '#/components/schemas/AddressFormat'

    WalletParams:
      type: object
      required:
        - walletName
        - accounts
      properties:
        walletName:
          type: string
          description: Human-readable name for a Wallet.
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/WalletAccountParams'
          description: A list of wallet Accounts. This field, if not needed, should be an empty array in your request body.
        mnemonicLength:
          type: integer
          format: int32
          description: Length of mnemonic to generate the Wallet seed. Defaults to 12. Accepted values 12, 15, 18, 21, 24.

    WalletResult:
      type: object
      required:
        - walletId
        - addresses
      properties:
        walletId:
          type: string
        addresses:
          type: array
          items:
            type: string
          description: A list of account addresses.

