// @generated by Clientgen. DO NOT EDIT BY HAND

import Foundation
import TurnkeyTypes

extension TurnkeyClient {

  /// Get Account
  /// Return organization id associated with a given phone number, email, public key, credential ID or OIDC token.
  public func proxyGetAccount(_ input: ProxyTGetAccountBody) async throws
    -> ProxyTGetAccountResponse
  {
    return try await authProxyRequest("/v1/account", body: input)
  }

  /// OAuth 2.0 Authenticate
  /// Authenticate with an OAuth 2.0 provider and receive an OIDC token issued by Turnkey in response.
  public func proxyOAuth2Authenticate(_ input: ProxyTOAuth2AuthenticateBody) async throws
    -> ProxyTOAuth2AuthenticateResponse
  {
    return try await authProxyRequest("/v1/oauth2_authenticate", body: input)
  }

  /// OAuth Login
  /// Login using an OIDC token and public key.
  public func proxyOAuthLogin(_ input: ProxyTOAuthLoginBody) async throws
    -> ProxyTOAuthLoginResponse
  {
    return try await authProxyRequest("/v1/oauth_login", body: input)
  }

  /// Init OTP
  /// Initialize an OTP (email or SMS) for a user.
  public func proxyInitOtp(_ input: ProxyTInitOtpBody) async throws -> ProxyTInitOtpResponse {
    return try await authProxyRequest("/v1/otp_init", body: input)
  }

  /// OTP Login
  /// Login using a verification token and public key.
  public func proxyOtpLogin(_ input: ProxyTOtpLoginBody) async throws -> ProxyTOtpLoginResponse {
    return try await authProxyRequest("/v1/otp_login", body: input)
  }

  /// Verify OTP
  /// Verify the OTP code previously sent to the user's contact and return a verification token.
  public func proxyVerifyOtp(_ input: ProxyTVerifyOtpBody) async throws -> ProxyTVerifyOtpResponse {
    return try await authProxyRequest("/v1/otp_verify", body: input)
  }

  /// Signup
  /// Onboard a new user.
  public func proxySignup(_ input: ProxyTSignupBody) async throws -> ProxyTSignupResponse {
    return try await authProxyRequest("/v1/signup", body: input)
  }

  /// Get WalletKit Config
  /// Get wallet kit settings and feature toggles for the calling organization.
  public func proxyGetWalletKitConfig(_ input: ProxyTGetWalletKitConfigBody = .init()) async throws
    -> ProxyTGetWalletKitConfigResponse
  {
    return try await authProxyRequest("/v1/wallet_kit_config", body: input)
  }

}
